---
title: "Week 2 Assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

Create a web page using R Markdown that features a map created with Leaflet. Host your webpage on either GitHub Pages, RPubs, or NeoCities.  
Your webpage must contain the date that you created the document, and it must contain a map created with Leaflet. We would love to see you show off your creativity!


## 7th July 2020

```{r, echo = F}
library(leaflet)
tourSpot <- data.frame(lat = c(28.417839, 40.689249, 37.819929,43.0962, 37.865101),
                       lng = c(-81.581235, -74.044500, -122.478255, -79.0377, -119.538329))
tourSites <- c(
  "<a href='https://disneyworld.disney.go.com/'>Disney World</a>",
  "<a href='https://www.nps.gov/stli/index.htm'>Statue of Liberty</a>",
  "<a href='http://www.goldengatebridge.org/'>Golden Gate Bridge</a>",
  "<a href='https://www.niagarafallsusa.com/'>Niagra Fall</a>",
  "<a href='https://www.nps.gov/yose/index.htm'>Yosemite National Park</a>"
)
tourSpot %>% leaflet() %>% addTiles() %>% addMarkers(popup = tourSites)
```
